"""initial

Revision ID: 053c3e91f6be
Revises: 
Create Date: 2021-07-22 08:30:44.805097

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "053c3e91f6be"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("saleor_domain", sa.String(length=255), nullable=True),
        sa.Column("auth_token", sa.String(length=255), nullable=True),
        sa.Column("webhook_id", sa.String(length=255), nullable=True),
        sa.Column("webhook_secret", sa.String(length=255), nullable=True),
        sa.Column("algolia_app_id", sa.String(length=255), nullable=True),
        sa.Column("algolia_api_key", sa.String(length=255), nullable=True),
        sa.Column("languages_list", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("transformation_service_url", sa.Text(), nullable=True),
        sa.Column("transformation_service_api_key", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("saleor_domain"),
    )
    op.create_table(
        "configuration_activewebhooks",
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.Column("configuration_webhook_id", sa.Integer(), nullable=False),
        sa.Column(
            "transformation_type",
            sa.Enum("LOCAL", "REMOTE", name="transformationtype"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["configurations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["configuration_webhook_id"],
            ["configuration_webhooks.id"],
        ),
        sa.PrimaryKeyConstraint("configuration_id", "configuration_webhook_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("configuration_activewebhooks")
    op.drop_table("configurations")
    op.drop_table("configuration_webhooks")
    # ### end Alembic commands ###
